/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteKarzaPanArgs } from "./DeleteKarzaPanArgs";
import { KarzaPanFindManyArgs } from "./KarzaPanFindManyArgs";
import { KarzaPanFindUniqueArgs } from "./KarzaPanFindUniqueArgs";
import { KarzaPan } from "./KarzaPan";
import { KarzaPanService } from "../karzaPan.service";
@graphql.Resolver(() => KarzaPan)
export class KarzaPanResolverBase {
  constructor(protected readonly service: KarzaPanService) {}

  async _karzaPansMeta(
    @graphql.Args() args: KarzaPanFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [KarzaPan])
  async karzaPans(
    @graphql.Args() args: KarzaPanFindManyArgs
  ): Promise<KarzaPan[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => KarzaPan, { nullable: true })
  async karzaPan(
    @graphql.Args() args: KarzaPanFindUniqueArgs
  ): Promise<KarzaPan | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => KarzaPan)
  async deleteKarzaPan(
    @graphql.Args() args: DeleteKarzaPanArgs
  ): Promise<KarzaPan | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
